'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3082
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VBP04721.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property About() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("About", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Align_Centre_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Align-Centre-3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Align_Left_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Align-Left-3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Align_Right_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Align-Right-3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bold_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bold-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Borders_All() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Borders-All", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Borders_All1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Borders-All1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Borders_Inside() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Borders-Inside", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Briefcase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Briefcase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Calendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Chart1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chart1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cross() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cross", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Database() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Database", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Delete_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete-Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Execute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Execute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Export_Excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Export-Excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Export_Excel1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Export-Excel1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Export_HTML() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Export-HTML", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Folder_Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder-Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Folder_New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder-New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Grid_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grid-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Help_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Italic_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Italic-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_prex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo prex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Messenger_Information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Messenger-Information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mm_Fast_Forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mm-Fast Forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mm_First() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mm-First", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mm_Last() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mm-Last", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mm_Rewind() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mm-Rewind", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Note() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Note", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Note_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Note-Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Note_Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Note-Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Note_Edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Note-Edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Note_New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Note-New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Note1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Note1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Redo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Redo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Report_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Report-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Select_All_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Select All-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Underline_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Underline-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property User() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Window_Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Window-Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Window_New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Window-New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Window_Object() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Window-Object", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Window_Properties() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Window-Properties", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Work_Sheet_New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Work Sheet-New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
